name: Plutselig Sirkus
favicon: null
layout_spectrum: 0.7024959123227745
typography_spectrum: 0.5283395042642951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0e0c7'
    - '#1b6e88'
    - '#d3a957'
    - '#ef5441'
    - '#5d919b'
  brandStrength: 0.5625
  lightness: 0.5443586383480579
  saturation: 0.17247259686701
  rhythmicContrast: 0.6977991997264326
purpose: []
