name: Plutselig Sirkus
favicon: null
layout_spectrum: 0.34412
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ba875e'
    - '#f6d3ac'
    - '#ff373d'
    - '#9d051e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
